### ISSUE TITLE
Ensure the class is annotated with Introspected

### ISSUE THREAD

**Issue by mrugesh-roambee** [micronaut-projects/micronaut-data#1182]
### Expected Behavior

`@Audited ` on any entity should audit that entity.

### Actual Behaviour

Error I get: Ensure the class is annotated with Introspected even if I add annotation `@Introspected` on my entityThe error

### Steps To Reproduce

Steps are listed here:
https://stackoverflow.com/questions/69315854/ensure-the-class-is-annotated-with-introspected

Even if I follow example application the error I get is,

`21:00:26.223 [io-executor-thread-2] DEBUG c.r.e.web.rest.CustomerResource - REST request to get all Customers
21:00:48.329 [io-executor-thread-4] DEBUG c.r.e.web.rest.CustomerResource - REST request to save Customer : Customer{id=null, uuid='35c6cbea-5e08-4d60-9d65-ec721c0b5c62', name='fsdd', desc='ssdf', active='ACTIVE', createdBy=3, createdAt='2021-03-23T18:30:00Z', updatedBy=3, updatedAt='2021-09-23T18:30:00Z'}
21:00:48.502 [io-executor-thread-6] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Unable to perform beforeTransactionCompletion callback: No bean introspection available for type [interface java.util.Map]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
org.hibernate.HibernateException: Unable to perform beforeTransactionCompletion callback: No bean introspection available for type [interface java.util.Map]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected`

### Environment Information

```
<maven.version>3.3.9</maven.version>
<java.version>13</java.version>
<node.version>v12.16.1</node.version>
<npm.version>6.14.5</npm.version>
<micronaut.version>2.4.4</micronaut.version>
<hibernate.version>5.4.24.Final</hibernate.version>
```

### Example Application
https://github.com/jachinte/micronaut-hibernate-envers

_No response_

### Version

2.4.4

**Comment by dstepanov** [comment]
This have been fixed a long time ago.

**Comment by mrugesh-roambee** [comment]
I am using below setup, and still face this issue.
MHipster v1.0.2 :: Running Micronaut v2.4.4
JHipster version: 6.10.5

**Comment by dstepanov** [comment]
Please try the latest 2X release 2.5.12 or 3X release 3.0.2
