### ISSUE TITLE
JpaSpecificationExecutor causes NullPointerException when fetching entities having @Transient properties

### ISSUE THREAD

**Issue by davidsonnabend** [micronaut-projects/micronaut-data#3519]
### Expected Behavior

Using the `JpaSpecificationExecutor` with Mirconaut 4.9.3 works the same way as with Micronaut 4.9.2.

### Actual Behaviour

Querying entities having a `@Transient` property causes a `NullPointerException` when using the `JpaSpecificationExecutor`.

Assuming the following example entity:

```kotlin
@MappedEntity
data class Foo(
    @Id
    @GeneratedValue
    val id: Long? = null,

    @Version
    val version: Long? = null,

    val name: String? = null,
) {

    @Transient
    fun getSomeValue() = 10
}
```

And the following repository:

```kotlin
@JdbcRepository(dialect = Dialect.POSTGRES)
interface FooRepository : CrudRepository<Foo, Long>, JpaSpecificationExecutor<Foo>
```

When trying to fetch entities using a `PredicateSpecification`:

```kotlin
fooRepository.findAll(where<Foo> { root.get<String>("name") eq "test" })
```

The following `NullPointerException` is thrown:

```kotlin
java.lang.NullPointerException: Cannot invoke "io.micronaut.data.model.runtime.RuntimePersistentProperty.getName()" because "property" is null
                at io.micronaut.data.model.runtime.RuntimePersistentEntity.getPropertyByNameIgnoreCase(RuntimePersistentEntity.java:356)
                at io.micronaut.data.runtime.criteria.AbstractRuntimePersistentEntityJoinSupport.get(AbstractRuntimePersistentEntityJoinSupport.java:70)
                at io.micronaut.data.runtime.criteria.AbstractRuntimePersistentEntityJoinSupport.get(AbstractRuntimePersistentEntityJoinSupport.java:36)
                at com.example.FooRepositoryTest$1$1$1$1.invoke(FooRepositoryTest.kt:15)

```

### Steps To Reproduce

1. Clone the example application
2. Run the test suite
3. See the test report

### Environment Information

- Operating System: Ubuntu 24.04
- JDK Version: 21.0.8-graal

### Example Application

https://github.com/davidsonnabend/micronaut-data-transient-properties

### Version

4.9.3

**Comment by davidsonnabend** [comment]
Looks like the fix should be pretty simple. An additional `null` check in `RuntimePersistentEntity::getPropertyByNameIgnoreCase` should be fine:

```java
    @Override
    public RuntimePersistentProperty<T> getPropertyByNameIgnoreCase(String name) {
        for (RuntimePersistentProperty<T> property : allPersistentProperties) {
            String propertyName = property.getName();
            if (propertyName != null && propertyName.equalsIgnoreCase(name)) {
                return property;
            }
        }
        return null;
    }
```

I'm not sure where/how to add a suitable test. If some one could assist, I can create a PR.

**Comment by radovanradic** [comment]
Should be fixed by https://github.com/micronaut-projects/micronaut-data/pull/3523

**Comment by davidsonnabend** [comment]
Unfortunately, I haven't tested the fix locally against the reproducer. And as I wasn't able to reproduce the error in the Micronaut Data testsuite, I didn't see that the suggested change did not fix the issue.

As `property` is `null` the NPE is still thrown. 🙈

Could you please reopen the issue and a will provide a new PR.
